Repository DataDog/pprof-nodejs, pull requests merged in 2023-08, with the labels that each got.

#121 Fix bug in profiler map
  bindings/profilers/wall.cc
  ts/src/profile-serializer.ts
  ts/test/test-worker-threads.ts
  ts/test/worker.ts
Labels: bug, semver-patch

#123 doc: update references to pprof package
  README.md
Labels: documentation, semver-patch

#125 Workaround v8 bug
  bindings/profilers/wall.cc
  bindings/profilers/wall.hh
  package-lock.json
  ts/src/index.ts
  ts/src/time-profiler.ts
  ts/test/test-time-profiler.ts
Labels: bug, semver-patch

#128 Remove Node 12 support
  .github/workflows/build.yml
  .github/workflows/release.yml
  README.md
  bindings/profilers/heap.cc
  package-lock.json
  package.json
Labels: semver-major

#131 Target ES2020 language
  tsconfig.json
Labels: semver-major
